#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Mar 15, 2022 09:55:48 AM +03  platform: Windows NT


import tkinter as tk

from tkinter.constants import *
import os
import ultimateUiDesignWithTabs





def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = ultimateUiDesignWithTabs.WholeWindow(_top1)
    root.mainloop()
    
if __name__ == '__main__':
    ultimateUiDesignWithTabs.start_up()




